services:
  app:
    build: 
      context: .
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - .air.toml:/app/.air.toml
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: develop
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    